# Generated by Django 4.2.2 on 2023-06-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj_auto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmenInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wichtigeInfo', models.CharField(blank=True, max_length=1000)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('adresse', models.CharField(blank=True, max_length=150)),
                ('facebookLink', models.CharField(blank=True, max_length=1000)),
                ('twitterLink', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('hours', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
