# Generated by Django 4.2.2 on 2023-06-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj_auto', '0002_firmeninfos_openinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmeninfos',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
