# Generated by Django 4.2.2 on 2023-06-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tj_auto', '0003_alter_firmeninfos_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghours',
            options={'ordering': ['day_number']},
        ),
        migrations.AddField(
            model_name='openinghours',
            name='day_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
